# Generated by Django 3.2.3 on 2022-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('university_name', models.CharField(default='', max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
                ('event_name', models.CharField(default='', max_length=100)),
                ('event_date', models.CharField(default='', max_length=100)),
                ('U_ID', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
