# Generated by Django 3.2.3 on 2022-07-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0005_auto_20220621_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name_plural': 'Attendees'},
        ),
    ]
