# Generated by Django 3.2.3 on 2023-02-07 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0006_auto_20220706_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='csv/')),
            ],
        ),
    ]
