# Generated by Django 3.2.3 on 2023-02-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0007_csv_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='csv_file_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='certs.csv_files'),
        ),
    ]
