# Generated by Django 3.2.3 on 2023-02-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0008_participants_csv_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='csv_file_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='certs.csv_files'),
        ),
    ]
