# Generated by Django 3.2.3 on 2023-02-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0012_alter_participants_csv_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
