# Generated by Django 3.2.3 on 2023-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0013_participants_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
