# Generated by Django 3.2.3 on 2023-02-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0014_auto_20230215_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_files',
            name='csv_file',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
