# Generated by Django 3.2.3 on 2023-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0015_alter_csv_files_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='emp_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
